data:
    #data: "/home/arsen/data/data_conventional"
    #data: "/home/arsen/data/data_stable"
    data: "/home/arsen/data/data_primitive_train"
    data_test: "/home/arsen/data/data_primitive_test"
    #data_test: "/home/arsen/data/data_stable_test"
    #phonopy: "/home/arsen/data/phonopy_conventional"
    phonopy: "/home/arsen/data/phonopy_primitive"
    num_workers: 0
    #shared_memory_size: "30G"

model:
  emb_size: 128
  out_emb_size: 128
  int_emb_size: 64
  #emb_size: 64
  #out_emb_size: 64
  #int_emb_size: 32
  basis_emb_size: 8
  num_blocks: 4
  num_spherical: 7
  num_radial: 6
  envelope_exponent: 5
  cutoff: 5.0
  extensive: True
  num_before_skip: 1
  num_after_skip: 2
  num_dense_output: 3

diffusion:
    #beta_schedule: linear
    #beta_start: 0.0001
    #beta_end: 0.02
    beta_schedule: log
    beta_start: 0.0001
    beta_end: 10.
    num_diffusion_timesteps: 15

lattice_diffusion:
    lengths_mult: 1.
    angles_mult: 1.
    num_diffusion_timesteps: 15

training:
    #batch_size: 128
    batch_size: 32
    n_epochs: 10000
    n_iters: 5000000
    snapshot_freq: 500
    validation_freq: 2000
    add_atoms_poisson_l_per_atom: 0.2  # controls the probability of atoms being added during diffusion
    lattice_loss_coef: 1.  # lattice noise loss multiplier
    count_loss_coef: 0.5  # atom number loss multiplier

sampling:
    last_only: True
    n_atoms_constant: True
    n_atoms_lambda: 10.0
    remove_atom_mult: 3.0
    #ckpt_id: 11000
    max_t: 1000  # cap the timestep passed to the model during sampling 
    #sample_structure: "/home/arsen/data/my_data_cif_test/mp-1077918.cif"  # structure to borrow the composition/lattice from
    #sample_structure: "/home/arsen/data/my_data_cif_test/mp-1084850.cif"  # structure to borrow the composition/lattice from
    #sample_structure: "/home/arsen/data/my_data_cif_test/mp-1201721.cif"
    
    #sample_structure: "/home/arsen/data/data_stable_test/mp-189.cif" # Si Ru
    #sample_structure: "/home/arsen/data/data_stable_test/mp-706.cif" # Hg F
    #sample_structure: "/home/arsen/data/data_stable_test/mp-1205044.cif" # C N Si Gd
    #sample_structure: "/home/arsen/data/data_stable_test/mp-1205483.cif" # Tm C N
    #sample_structure: "/home/arsen/data/data_stable_test/mp-718.cif" # Pd Sn
    #sample_structure: "/home/arsen/data/data_stable_test/mp-1057.cif" # Al Ni
    #sample_structure: "/home/arsen/data/data_stable_test/mp-1078832.cif" # Zr Ga Ni
    composition_dict:
        Li: 4
        B: 4
        H: 16
    lattice_noise: True
    lattice_noise_mult: 150.

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0002
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
    grad_clip: 1.0
    
test:
    noise_rolls: 1
    timestep_min: 0
    timestep_max: 19
